# Generated by Django 3.1.6 on 2021-02-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transactions_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='AccountTransactions',
        ),
    ]
