# Generated by Django 3.1.6 on 2021-02-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210213_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransactions',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=200, null=True),
        ),
    ]
